secrets:
    # password per l'utente del database
    MONGO_USER_PW:
        file: lib/secrets/MONGO_ROOT_PW
    # configurazione per l'invio di email
    MAIL_CONFIG:
        file: lib/secrets/MAIL_CONFIG
    # certificato per la firma dei JWT
    JWT_CERT:
        file: lib/secrets/certs/auth.crt
    # chiave per la firma dei JWT
    JWT_KEY:
        file: lib/secrets/keys/auth.key

##########################################
services:
    auth:
        build:
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: auth-backend
        environment:
            MODE: DEVELOPMENT
            FRONTEND_HOST: "http://localhost:4200" # HOST con protocollo, porta e prefix
            TZ: Europe/Rome
            MONGO_USER: root
            MONGO_DB: auth
            MONGO_HOST: mongo1.dag.lan:27017,mongo2.dag.lan:27017,mongo3.dag.lan:27017
            REGISTRATION_BEHAVIOUR: "ALLOW_ANYBODY" # "ONLY_ADMIN" 
        ports:
            - 8000:8000
        volumes:
            - ./api:/app
        secrets:
            - MAIL_CONFIG
            - MONGO_USER_PW
            - JWT_CERT
            - JWT_KEY
