FROM python:3.13

# Set the working directory
WORKDIR /app

# Copy the backend directory contents into the container at /app
COPY ./backend/requirements.txt ./

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

ENV MONGO_HOST=db:27017
ENV MONGO_USER=auth_user
ENV MONGO_DB=auth_db
ENV FRONTEND_HOST="http://localhost:4200"
ENV MODE="DEVELOPMENT"
ENV REGISTRATION_BEHAVIOUR="ALLOW_ANYBODY"

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Run app when the container launches
CMD [ "python", "-u", "./main.py" ]
# la -u è per mostrare i print nel log (UNBUFFERED=1)
