networks:
    # rete per la comunicazione interna dei containers
    auth-net:
        name: auth-net

    # rete di default per la comunicazione con il proxy,
    # da instanziare solo sui containers che si espongono
    # default:
    #     name: traefik_net
    #     external: true

##########################################
secrets:
    MONGO_ROOT_PW:
        file: lib/secrets/MONGO_ROOT_PW
    MONGO_USER_PW:
        file: lib/secrets/MONGO_AUTHUSER_PW
    MAIL_CONFIG:
        file: lib/secrets/MAIL_CONFIG
    JWT_CERT:
        file: lib/secrets/certs/auth.crt
    JWT_KEY:
        file: lib/secrets/keys/auth.key

##########################################
volumes:
    auth-vol:
        name: auth-vol

##########################################
services:
    backend:
        build:
            context: ./
            dockerfile: Dockerfile.dev.api
        restart: unless-stopped
        container_name: auth-backend
        environment:
            MODE: DEVELOPMENT
            FRONTEND_HOST: "http://localhost:4200" # HOST con protocollo, porta e prefix
            TZ: Europe/Rome
            MONGO_USER: authuser
            MONGO_DB: auth
            MONGO_HOST: db:27017
        networks:
            - auth-net
            - default
        ports:
            - 8000:8000
        volumes:
            - ./backend:/app
            # - /etc/timezone:/etc/timezone:ro
            # - /etc/localtime:/etc/localtime:ro
        secrets:
            - MAIL_CONFIG
            - MONGO_USER_PW
            - JWT_CERT
            - JWT_KEY

        # network_mode: "bridge"

    db:
        image: mongo:7
        restart: unless-stopped
        container_name: db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/MONGO_ROOT_PW
            MONGO_USER: authuser
            MONGO_DB: auth
            # MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PW:?error}
        ports:
            - 27017:27017  # eliminare in PRODUCTION
        networks:
            - auth-net
        volumes:
            - auth-vol:/data/db # il database è salvato nel volume di docker
            - ./db/init:/docker-entrypoint-initdb.d # esegui i file al primo avvio
        secrets:
            - MONGO_ROOT_PW
            - MONGO_USER_PW
