FROM python:3.12

# Set the working directory
WORKDIR /app

# Copy the backend directory contents into the container at /app
COPY ./backend/requirements.txt ./

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Run app when the container launches
CMD [ "python", "-u", "./main.py" ]
# la -u è per mostrare i print nel log (UNBUFFERED=1)
